name: core-text
version: 0.2.0.1
synopsis: A rope type based on a finger tree over UTF-8 fragments
description: |
  A rope data type for text, built as a finger tree over UTF-8 text
  fragments. The package also includes utiltiy functions for breaking and
  re-wrapping lines, conveniences for pretty printing and colourizing
  terminal output, and a simple mechanism for multi-line Rope literals.
  
  The main @Rope@ type and its usage are described at "Core.Text.Rope" in
  this package.
  
  This is part of a library intended to ease interoperability and assist in
  building command-line programs, both tools and longer-running daemons.
  A list of features and some background to the library's design is contained
  in the
  <https://github.com/oprdyn/unbeliever/blob/master/README.markdown README>
  on GitHub.

stability: experimental
license: BSD3
license-file: LICENCE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2018-2019 Operational Dynamics Consulting Pty Ltd, and Others
tested-with: GHC == 8.6.5
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: oprdyn/unbeliever

dependencies:
 - base >= 4.11 && < 5
 - bytestring
 - deepseq
 - fingertree
 - hashable
 - prettyprinter
 - prettyprinter-ansi-terminal
 - template-haskell
 - text
 - text-short

library:
  source-dirs: lib
  exposed-modules:
   - Core.Text
   - Core.Text.Bytes
   - Core.Text.Rope
   - Core.Text.Utilities
  other-modules:
   - Core.Text.Breaking

