name: core-streaming
version: 0.0.1.0
synopsis: Opinionated Haskell Interoperability
description: |
  Streaming I/O.

  This is part of a library intended to ease interoperability and assist in
  building command-line programs, both tools and longer-running daemons.
  A list of features and some background to the library's design is contained
  in the
  <https://github.com/oprdyn/unbeliever/blob/master/README.markdown README>
  on GitHub.
  
  See "Core.Streaming.InputOutput" to get started.

stability: experimental
license: BSD3
license-file: LICENCE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2018-2019 Operational Dynamics Consulting Pty Ltd, and Others
tested-with: GHC == 8.6.5
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: oprdyn/unbeliever

dependencies:
 - async
 - base >= 4.11 && < 5
 - bytestring
 - mtl
 - safe-exceptions
 - stm
 - template-haskell
 - terminal-size
 - transformers

library:
  dependencies:
   - core-text
   - core-data
   - core-program
   - io-streams
  source-dirs: lib
  exposed-modules:
   - Core.Streaming.InputOutput
  other-modules: []
